### ISSUE TITLE
[DOC] include a HOWTO add dependency

### ISSUE THREAD

**Issue by teymour** [apereo/cas-gradle-overlay-template#1]
I try to generate a WAR for CAS  with Ldap.

Apparently, a dependency to « cas-server-support-ldap » has to be declare but i have no idea how to do it with gradle :-(

It would be great to have a documentation associated with your project explaining to people like me (who  know nothing about gradle) how to add there kind of dependencies.

Thanks anyway for your work, I was surprised how simple it was to build a war for the latest version of CAS.

**Comment by mmoayyed** [comment]
Dependencies are declared here https://github.com/apereo/cas-gradle-overlay-template/blob/master/cas/build.gradle#L18

Follow the same sort of pattern.

**Comment by teymour** [comment]
Thanks for your answer.

I could generate a war.

Just in case someone wonders in the future, here is how i declared the LDAP dependencies : https://github.com/24eme/cas-gradle-ldap/blob/master/cas/build.gradle#L22

**Comment by mmoayyed** [comment]
Very good. I am not sure this is worthy to document yet, because it's superfluous to document what Gradle already has documented perfectly. If you are familiar with Gradle, you'd know how to declare modules and dependencies for any given gradle project. So sorry for not being clearer, but that's as far as we'd go to point you to Gradle itself. 

If you find other issues with the gradle build, post back. We'll eventually produce one for 5.
